#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_ballot : require

#include "../../../Includes/Core.glsl"
#include "../../../Includes/Common/FrameGlobalContext.glsl"
#include "../../../Includes/Common/Camera.glsl"
#include "../../../Includes/Common/SpotLight.glsl"
#include "../../../Includes/Utils/CullingMath.glsl"
#include "../../../Includes/Common/IndirectCommand.glsl"
#include "../../../Includes/Utils/Occlusion.glsl"

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#include "../../../Includes/PushConstants/SpotLightCullingPC.glsl"

layout(push_constant) uniform PushConstants {
    SpotLightCullingPC pc;
};

layout(set = 2, binding = 0) uniform sampler2D depthPyramid;

void main() {
    FrameGlobalContext ctx = GET_FRAME_CONTEXT(pc.frameGlobalContextBufferAddr);

    uint globalId = gl_GlobalInvocationID.x;
    if (globalId >= ctx.spotLightCount) return;

    SpotLightColliderGPU collider = GET_SPOT_LIGHT_COLLIDER(ctx.spotLightColliderBufferAddr, globalId);

    uint cameraIdx = GET_SPARSE_INDEX(ctx.cameraSparseMapBufferAddr, ctx.mainCameraEntity);
    CameraComponent camera = GET_CAMERA(ctx.cameraBufferAddr, cameraIdx);

    // 1. Frustum Culling (Sphere + AABB)
    uint visibility = INTERSECTION_INTERSECT;
    if(ctx.enableSpotLightFrustumCulling == 1)
    {
        uint visibility = TestFrustum(collider.center, collider.radius, collider.aabbMin, collider.aabbMax, camera);
        if (visibility == INTERSECTION_OUTSIDE) return;
    }

    // 2. Occlusion and 0-pixel Culling
    float screenSizePixels = 0.0;
    vec2 screenRes = vec2(ctx.screenWidth, ctx.screenHeight);
    bool enableDepthOcclusion = (ctx.enableSpotLightOcclusionCulling == 1);

    if (IsSphereOccludedPerspective(collider.center, collider.radius, camera.view, camera.projVulkan, camera.params.x, camera.params.y, depthPyramid, screenRes, enableDepthOcclusion, screenSizePixels)) {
        return;
    }

    uint denseIdx = GET_SPARSE_INDEX(ctx.spotLightSparseMapBufferAddr, collider.entityIndex);

    uint needsWrite = 1;
    uint subgroupWriteCount = subgroupAdd(needsWrite);
    uint localOffset = subgroupExclusiveAdd(needsWrite);
    uint baseOffset = 0;

    if (subgroupElect()) {
        baseOffset = atomicAdd(GET_VK_DRAW_CMD(ctx.spotLightIndirectCommandBufferAddr, 0).instanceCount, subgroupWriteCount);
    }

    baseOffset = subgroupBroadcastFirst(baseOffset);
    uint finalIndex = baseOffset + localOffset;
    GET_VISIBLE_SPOT_LIGHT(ctx.spotLightVisibleIndexBufferAddr, finalIndex) = collider.entityIndex;

    uint shadowSparseIdx = GET_SPARSE_INDEX(ctx.spotLightShadowSparseMapBufferAddr, collider.entityIndex);
    if (shadowSparseIdx != INVALID_INDEX) 
    {
        uint needsShadowWrite = 1;
        uint shadowSubgroupWriteCount = subgroupAdd(needsShadowWrite);
        uint shadowLocalOffset = subgroupExclusiveAdd(needsShadowWrite);
        uint shadowBaseOffset = 0;
        
        if (subgroupElect()) {
            shadowBaseOffset = atomicAdd(GET_VISIBLE_COUNT_DATA(ctx.spotLightShadowVisibleCountBufferAddr), shadowSubgroupWriteCount);
        }
        
        shadowBaseOffset = subgroupBroadcastFirst(shadowBaseOffset);
        uint finalShadowIndex = shadowBaseOffset + shadowLocalOffset;
        GET_VISIBLE_SHADOW_SPOT_LIGHT(ctx.spotLightVisibleShadowIndexBufferAddr, finalShadowIndex) = collider.entityIndex;
    }
}