// Copyright (C) 2026 Tamás Péter
// This file is part of SynapseEngine.
//
// SynapseEngine is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SynapseEngine is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with SynapseEngine. If not, see <https://www.gnu.org/licenses/>.

#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_ballot : require

#include "../../../Includes/Core.glsl"
#include "../../../Includes/Common/FrameGlobalContext.glsl"
#include "../../../Includes/Common/Camera.glsl"
#include "../../../Includes/Common/Transform.glsl"
#include "../../../Includes/Common/Tag.glsl"
#include "../../../Includes/Common/Model.glsl"
#include "../../../Includes/Common/Mesh.glsl"
#include "../../../Includes/Common/Animation.glsl"
#include "../../../Includes/Common/Material.glsl"
#include "../../../Includes/Common/Culling.glsl"
#include "../../../Includes/Common/SpotLight.glsl"
#include "../../../Includes/Utils/CullingMath.glsl"
#include "../../../Includes/Utils/Occlusion.glsl"
#include "../../../Includes/Utils/CullingUtils.glsl"

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#include "../../../Includes/PushConstants/SpotLightShadowCullingPC.glsl"

layout(push_constant) uniform PushConstants {
    SpotLightShadowCullingPC pc;
};

layout(set = 2, binding = 0) uniform sampler2D shadowDepthPyramid;

void main() 
{
    FrameGlobalContext ctx = GET_FRAME_CONTEXT(pc.frameGlobalContextBufferAddr);

    uint offset = ctx.staticTransformCount * ctx.enableSpotLightBvhCulling;
    uint transformDenseIndex = gl_GlobalInvocationID.x + offset;
    uint transformCount = ctx.allTransformCount - offset;

    // Thread mapping: X = Model, Y = Light Index
    uint lightIdx = gl_GlobalInvocationID.y;
    if (gl_GlobalInvocationID.x >= transformCount) return;

    uint activeSpotLightShadowCount = GET_SPOT_VISIBLE_COUNT_DATA(ctx.spotLightShadowVisibleCountBufferAddr);
    if (lightIdx >= activeSpotLightShadowCount) return; 

    // 2. Resolve Entity and Model Data
    TransformModelLink link = GET_TRANSFORM_MODEL_LINK(ctx.transformModelLinkBufferAddr, transformDenseIndex);
    if (link.modelDenseIndex == INVALID_INDEX) return;
    uint entityId = link.entityIndex;

    uint tagSparseIndex = GET_SPARSE_INDEX(ctx.tagSparseMapBufferAddr, entityId);
    if (tagSparseIndex == INVALID_INDEX) return;

    uint entityFlags = GET_TAG_DATA(ctx.tagDataBufferAddr, tagSparseIndex);
    bool isActive = (entityFlags & (1u << 0)) != 0;
    if (!isActive) return;

    ModelComponent modelComp = GET_MODEL_COMP(ctx.modelBufferAddr, link.modelDenseIndex);
    bool castShadow = (modelComp.flags & (1u << 0)) != 0;
    if (modelComp.modelIndex == INVALID_INDEX || !castShadow) return;


    // 3. Resolve Transform, Camera & Colliders
    TransformComponent transform = GET_TRANSFORM(ctx.transformBufferAddr, transformDenseIndex);
    uint cameraIdx = GET_SPARSE_INDEX(ctx.cameraSparseMapBufferAddr, ctx.mainCameraEntity);
    CameraComponent camera = GET_CAMERA(ctx.cameraBufferAddr, cameraIdx);

    ModelAllocationInfo mAlloc = GET_MODEL_ALLOC(ctx.globalModelAllocationBufferAddr, modelComp.modelIndex);
    GpuModelAddresses addrs = GET_MODEL_ADDRESSES(ctx.modelAddressBufferAddr, modelComp.modelIndex);
    GpuMeshCollider localGlobalCollider = addrs.globalCollider;
    
    if(ctx.animationSparseMapBufferAddr != 0) {
        uint animSparseIndex = GET_SPARSE_INDEX(ctx.animationSparseMapBufferAddr, entityId);
        if (animSparseIndex != INVALID_INDEX) {
            AnimationComponent animComp = GET_ANIM_COMP(ctx.animationBufferAddr, animSparseIndex);
            if (animComp.animationIndex != INVALID_INDEX) {
                GpuAnimationAddresses animAddrs = GET_ANIM_ADDRESSES(ctx.animationAddressBufferAddr, animComp.animationIndex);

                if (animAddrs.isReady == 1) {
                    localGlobalCollider = GET_MESH_COLLIDER(animAddrs.frameGlobalColliders, animComp.frameIndex);
                }
            }
        }
    }
    
    GpuMeshCollider worldCollider = TransformCollider(localGlobalCollider, transform.transform);

    // 4. Resolve Spot Light Shadow Data
    uint lightEntity = GET_SPOT_VISIBLE_SHADOW_LIGHT(ctx.spotLightVisibleShadowIndexBufferAddr, lightIdx);
    uint lightDenseIndex = GET_SPARSE_INDEX(ctx.spotLightSparseMapBufferAddr, lightEntity);
    uint lightShadowDenseIndex = GET_SPARSE_INDEX(ctx.spotLightShadowSparseMapBufferAddr, lightEntity);
    SpotLightColliderGPU lightCollider = GET_SPOT_LIGHT_COLLIDER(ctx.spotLightColliderBufferAddr, lightDenseIndex);
    SpotLightShadowComponent shadowComp = GET_SPOT_LIGHT_SHADOW(ctx.spotLightShadowDataBufferAddr, lightShadowDenseIndex);

    // 5. Cone Culling against Spot Light
    uint visibility = INTERSECTION_INTERSECT;
    if(ctx.enableModelFrustumCulling == 1) {
        visibility = TestConeSphereState(lightCollider.worldPos, lightCollider.worldDir, lightCollider.range, lightCollider.outerAngleCos, lightCollider.outerAngleSin, worldCollider.center, worldCollider.radius);
        if (visibility == INTERSECTION_OUTSIDE) return;
    }

    // 6. Calculate LOD (Screen size)
    float cameraNear = GET_CAMERA_NEAR(camera);
    vec2 screenRes = vec2(ctx.screenWidth, ctx.screenHeight);  
    float mainCamScreenSize = CalculateSphereScreenSizePerspective(worldCollider.center, worldCollider.radius, camera.view, camera.proj, cameraNear, screenRes);

    if (mainCamScreenSize < 1.0) 
        return;

    uint entityData = (entityId & 0x7FFFFFFF);
    entityData = SET_BIT_TO(entityData, 31, visibility == INTERSECTION_INSIDE);

    uint safeMeshCount = mAlloc.meshAllocationCount / 4;

    // 9. Fast-Path
    if (IsModelSimpleEnoughForFastPath(safeMeshCount, addrs.vertexCount)) {
        
        uint rawLod = CalculateLodFromScreenSize(mainCamScreenSize);
        uint lod = min(rawLod + ctx.spotLightShadowLodBias, 3u);

        for(uint m = 0; m < safeMeshCount; ++m) {
            uint matIdx = GET_MATERIAL_INDEX(ctx.materialLookupBufferAddr, modelComp.materialOffset + m);
            Material mat = GET_MATERIAL(ctx.materialBufferAddr, matIdx);

            uint matType = GetMaterialRenderType(mat);

            MeshAllocationInfo meshAlloc = GET_MESH_ALLOC(ctx.globalMeshAllocationBufferAddr, mAlloc.meshAllocationOffset + (m * 4) + lod);
            uint pipeIdx = GET_PIPELINE_INDEX(ctx.pipelineLookupBufferAddr, modelComp.pipelineOffset + m);

            if (meshAlloc.activeTypes[pipeIdx][matType] == 1) {
                
                uint indirectIdx = meshAlloc.indirectIndices[pipeIdx][matType];
                uint isMeshlet = (pipeIdx == PIPELINE_MESHLET) ? 1u : 0u;

                uint drawCallKey = (isMeshlet << 31) | (indirectIdx & 0x7FFFFFFF);
                uvec2 gpuPayload = uvec2(entityData, lightIdx);

                uint sortSlot = atomicAdd(GET_SPOT_VISIBLE_COUNT_DATA(ctx.spotLightShadowVisibleMeshCountBufferAddr), 1);
                GET_SPOT_DRAW_CALL_KEY_DATA(ctx.spotLightShadowDrawCallKeyBufferAddr, sortSlot) = drawCallKey;
                GET_SPOT_SORTED_VALUE(ctx.spotLightShadowSortValuesBufferAddr, sortSlot) = sortSlot;
                GET_SPOT_SHADOW_INSTANCE_UNSORTED(ctx.spotLightShadowUnsortedInstanceBufferAddr, sortSlot) = gpuPayload;
            }
        }
        return;
    }

    // 10. Slow-Path: Defer to Mesh Culling
    uint needsWrite = 1;
    uint subgroupWriteCount = subgroupAdd(needsWrite);
    uint localOffset = subgroupExclusiveAdd(needsWrite);
    uint baseOffset = 0;

    if (subgroupElect()) {
        baseOffset = atomicAdd(GET_DISPATCH_CMD(ctx.spotLightShadowModelCountBufferAddr).groupCountX, subgroupWriteCount);
    }

    baseOffset = subgroupBroadcastFirst(baseOffset);

    if (needsWrite == 1) {
        uint finalIndex = baseOffset + localOffset;
        
        uint modelPayload = (modelComp.modelIndex & 0xFFFFFu);
        modelPayload |= ((lightIdx & 0xFFFu) << 20);

        VisibleModelData outData;
        outData.entityId = entityData; // [Bit 31: FullyInside, Bits 0-30: pureEntityId]
        outData.modelIndex = modelPayload; // [Bits 20-31: LightIdx, Bits 0-19: pureModelIndex]
        
        GET_VISIBLE_MODEL(ctx.spotLightShadowModelVisibleIndexBufferAddr, finalIndex) = outData;
    }
}