#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#include "../../../Includes/Core.glsl"
#include "../../../Includes/Common/FrameGlobalContext.glsl"
#include "../../../Includes/Common/Mesh.glsl"
#include "../../../Includes/Common/SpotLight.glsl"
#include "../../../Includes/Common/Culling.glsl"

// Single thread execution
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

#include "../../../Includes/PushConstants/SpotLightShadowCullingPC.glsl"

layout(push_constant) uniform PushConstants {
    SpotLightShadowCullingPC pc;
};

void main() {
    FrameGlobalContext ctx = GET_FRAME_CONTEXT(pc.frameGlobalContextBufferAddr);

    uint visibleCount = GET_SPOT_VISIBLE_COUNT_DATA(ctx.spotLightShadowVisibleMeshCountBufferAddr);
  
    uint groupCountX = (visibleCount + 255u) / 256u;

    GET_DISPATCH_CMD(ctx.spotLightShadowFinalizeDispatchBufferAddr).groupCountX = groupCountX;
}