#version 460
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_GOOGLE_include_directive : require

#include "../../Includes/Core.glsl"
#include "../../Includes/Common/FrameGlobalContext.glsl"
#include "../../Includes/Common/IndirectCommand.glsl"
#include "../../Includes/Common/Culling.glsl"

#include "../../Includes/PushConstants/WireframeSetupPC.glsl"

layout(push_constant) uniform PushConstants {
    WireframeSetupPC pc;
};

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    FrameGlobalContext ctx = GET_FRAME_CONTEXT(pc.frameGlobalContextBufferAddr);

    uint id = gl_GlobalInvocationID.x;
    if (id >= ctx.globalIndirectCommandCount) return;

    uint activeInstances = 0;

    if (id < ctx.globalTraditionalCommandsCount) {
        activeInstances = GET_TRADITIONAL_CMD(ctx.globalIndirectCommandCount, id).instanceCount;
    } 
    else {
        uint64_t meshletBaseAddr = ctx.globalIndirectCommandCount + (ctx.globalTraditionalCommandsCount * 16ul);
        uint localCmdIndex = id - ctx.globalTraditionalCommandsCount;
        
        activeInstances = GET_MESHLET_CMD(meshletBaseAddr, localCmdIndex).groupCountX;
    }

    GET_TRADITIONAL_CMD(ctx.wireframeMeshAabbIndirectCommandBufferAddr, id).instanceCount = activeInstances;
    GET_TRADITIONAL_CMD(ctx.wireframeMeshSphereIndirectCommandBufferAddr, id).instanceCount = activeInstances;
}