// Copyright (C) 2026 Tamás Péter
// This file is part of SynapseEngine.
//
// SynapseEngine is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SynapseEngine is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with SynapseEngine. If not, see <https://www.gnu.org/licenses/>.

#version 460
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_GOOGLE_include_directive : require

#include "../../Includes/Core.glsl"
#include "../../Includes/Common/FrameGlobalContext.glsl"
#include "../../Includes/Common/IndirectCommand.glsl"
#include "../../Includes/Common/Culling.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

#include "../../Includes/PushConstants/WireframeSetupPC.glsl"

layout(push_constant) uniform PushConstants {
    WireframeSetupPC pc;
};

void main() {
    FrameGlobalContext ctx = GET_FRAME_CONTEXT(pc.frameGlobalContextBufferAddr);

    uint id = gl_GlobalInvocationID.x;
    if (id >= ctx.globalIndirectCommandCount) return;

    uint activeInstances = 0;

    if (id < ctx.globalTraditionalCommandsCount) {
        activeInstances = GET_TRADITIONAL_CMD(ctx.globalIndirectCommandBufferAddr, id).instanceCount;
    } 
    else {
        uint64_t meshletBaseAddr = ctx.globalIndirectCommandBufferAddr + (ctx.globalTraditionalCommandsCount * 16ul);
        uint localCmdIndex = id - ctx.globalTraditionalCommandsCount;
        
        activeInstances = GET_MESHLET_CMD(meshletBaseAddr, localCmdIndex).groupCountX;
    }

    GET_TRADITIONAL_CMD(ctx.wireframeMeshAabbIndirectCommandBufferAddr, id).instanceCount = activeInstances;
    GET_TRADITIONAL_CMD(ctx.wireframeMeshSphereIndirectCommandBufferAddr, id).instanceCount = activeInstances;
}