#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#include "../../Includes/Core.glsl"
#include "../../Includes/Common/Camera.glsl"
#include "../../Includes/Utils/DepthMath.glsl"

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 2, binding = 0) uniform sampler2D inOpaqueDepth;
layout(set = 2, binding = 1) uniform sampler2D inOpaqueTransparentDepth;
layout(set = 2, binding = 2, rg32f) uniform writeonly image2D outImage;

#include "../../Includes/PushConstants/HizLinearizeDepthPC.glsl"

layout(push_constant) uniform PushConstants {
   HizLinearizeDepthPC pc;
};

void main() {
    ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    if (pos.x >= int(pc.outImageSize.x) || pos.y >= int(pc.outImageSize.y)) return;

    uint cameraIdx = GET_SPARSE_INDEX(pc.cameraSparseMapBufferAddr, pc.activeCameraEntity);
    CameraComponent camera = GET_CAMERA(pc.cameraBufferAddr, cameraIdx);

    vec2 uv = (vec2(pos) + vec2(0.5)) / pc.outImageSize;
    float opaqueDepth = texture(inOpaqueDepth, uv).x;
    float opaqueTransparentDepth = texture(inOpaqueTransparentDepth, uv).x;

    float nearPlane = camera.params.x;
    float farPlane = camera.params.y;
    float linearOpaueDepth = ConvertDepthToLinearNormalized(opaqueDepth, nearPlane, farPlane);
    float linearOpaueTransparentDepth = ConvertDepthToLinearNormalized(opaqueTransparentDepth, nearPlane, farPlane);

    imageStore(outImage, pos, vec4(vec2(linearOpaueDepth, linearOpaueTransparentDepth), 0.0, 0.0));
}