#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#include "../../Includes/Core.glsl"
#include "../../Includes/Common/FrameGlobalContext.glsl"
#include "../../Includes/Common/PointLight.glsl"
#include "../../Includes/Common/Camera.glsl"
#include "../../Includes/Utils/DepthMath.glsl"

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 2, binding = 0) uniform sampler2D inDepth;
layout(set = 2, binding = 1, rg32f) uniform writeonly image2D outImage;

#include "../../Includes/PushConstants/HizLinearizeDepthPC.glsl"

layout(push_constant) uniform PushConstants {
   HizLinearizeDepthPC pc;
};

void main() {
    ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    if (pos.x >= int(pc.outImageSize.x) || pos.y >= int(pc.outImageSize.y)) return;

    FrameGlobalContext ctx = GET_FRAME_CONTEXT(pc.frameGlobalContextBufferAddr);

    float rawDepth = texelFetch(inDepth, pos, 0).x;
    float finalDepth = rawDepth;

    uint cellX = uint(pos.x) / POINT_SHADOW_MIN_BLOCK_SIZE;
    uint cellY = uint(pos.y) / POINT_SHADOW_MIN_BLOCK_SIZE;
    uint flatIndex = cellY * POINT_SHADOW_GRID_SIZE + cellX;

    uint entityId = GET_POINT_GRID_LOOK_UP_DATA(ctx.pointLightShadowGridLookupBufferAddr, flatIndex);

    if (entityId != 0xFFFFFFFF) {
        uint shadowDenseIdx = GET_SPARSE_INDEX(ctx.pointLightShadowSparseMapBufferAddr, entityId);

        if (shadowDenseIdx != INVALID_INDEX) {
            PointLightShadowComponent shadowComp = GET_POINT_LIGHT_SHADOW(ctx.pointLightShadowDataBufferAddr, shadowDenseIdx);
            
            float nearPlane = shadowComp.planes.x; 
            float farPlane = shadowComp.planes.y;

            finalDepth = ConvertDepthToLinearNormalized(rawDepth, nearPlane, farPlane);
        }
    }

    imageStore(outImage, pos, vec4(finalDepth, rawDepth, 0.0, 0.0));
}