//Todo: Better to use a const.glsl and define all of this there!
const float PI = 3.14159265359;

//Approximates the ratio of reflected and refrected lights on the surface.
//This returns ks, the specular part, so diffuse can be calculated from this.
//As the angle grows between the surface normal and view direction the surface reflection increases.
vec3 FresnelSchlick(float cosTheta, vec3 F0)
{
    return F0 + (1.0 - F0) * pow(clamp(1.0 - cosTheta, 0.0, 1.0), 5.0);
}  

//This is the PBR BRDF normal distribution function, which returns how much of the "microfacets" are aligned
//with the halfway vector. The algorithm takes the surface roughness parameter in account.
//[0] = Surface is a mirror, everything is aligned, a really bright small specular part is visible.
//[1] = Surface is full diffuse, no specular reflection is visible
float DistributionGGX(vec3 N, vec3 H, float roughness)
{
    float a      = roughness*roughness;
    float a2     = a*a;
    float NdotH  = max(dot(N, H), 0.0);
    float NdotH2 = NdotH*NdotH;
	
    float num   = a2;
    float denom = (NdotH2 * (a2 - 1.0) + 1.0);
    denom = PI * denom * denom;
	
    return num / denom;
}

//This is the PBR BRDF geometry function, which approximates how much self shadow is generated by "overlapping microfacets" 
//on the surface. As roughness increases, the microfacets become more disoriented, so the surface appears darker.
float GeometrySchlickGGX(float NdotV, float roughness)
{
    float r = (roughness + 1.0);
    float k = (r*r) / 8.0;

    float num   = NdotV;
    float denom = NdotV * (1.0 - k) + k;
	
    return num / denom;
}

//This is the full geometry function, not only the normal and view direction matters when calculating the effects, but 
//the normal and light relation too.
float GeometrySmith(vec3 N, vec3 V, vec3 L, float roughness)
{
    float NdotV = max(dot(N, V), 0.0);
    float NdotL = max(dot(N, L), 0.0);
    float ggx2  = GeometrySchlickGGX(NdotV, roughness);
    float ggx1  = GeometrySchlickGGX(NdotL, roughness);
	
    return ggx1 * ggx2;
}

//This function returns the radiant from a light source
vec3 ShadePhysicallyBased(vec3 albedo, vec3 normal, vec3 toEye, vec3 toLight, float roughness, float metalness, vec3 lightColor, float attenuation, float strength)
{
    vec3 F0 = vec3(0.04); 
    F0 = mix(F0, albedo, metalness);

    // Calculate per-light radiance
    vec3 N = normal;
    vec3 V = toEye;
    vec3 L = toLight;
    vec3 H = normalize(V + L);

    vec3 radiance = lightColor * attenuation * strength;   
        
    // cook-torrance brdf
    float NDF = DistributionGGX(N, H, roughness);        
    float G = GeometrySmith(N, V, L, roughness);      
    vec3 F = FresnelSchlick(max(dot(H, V), 0.0), F0);       
        
    vec3 kS = F;
    vec3 kD = vec3(1.0) - kS;
    kD *= 1.0 - metalness;	  
        
    vec3 numerator    = NDF * G * F;
    float denominator = 4.0 * max(dot(N, V), 0.0) * max(dot(N, L), 0.0) + 0.0001;
    vec3 specular     = numerator / denominator;  
            
    // add to outgoing radiance Lo
    float NdotL = max(dot(N, L), 0.0);                
    return (kD * albedo / PI + specular) * radiance * NdotL; //Lo, but differed shading
}