#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_AMDX_shader_enqueue : require

#include "../../../Includes/Core.glsl"
#include "../../../Includes/Common/FrameGlobalContext.glsl"
#include "../../../Includes/Common/Camera.glsl"
#include "../../../Includes/Common/Culling.glsl"
#include "../../../Includes/Utils/CullingMath.glsl"
#include "../../../Includes/Utils/Occlusion.glsl"
#include "../../../Includes/Common/StaticChunk.glsl"
#include "../../../Includes/Payload/WorkGraphCullingPayload.glsl"

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#include "../../../Includes/PushConstants/ModelMeshCullingPC.glsl"

layout(push_constant) uniform PushConstants {
    ModelMeshCullingPC pc;
};

// Depth pyramid (HZB) for main camera occlusion culling
layout(set = 2, binding = 0) uniform sampler2D depthPyramid;

// Output node targeting the Static Model level
layout(coalescing_node_amdx) out node_type GeometryWorkGraphStaticModelCullingNode;
layout(location = 0) out ChunkCullingPayload payloadOut;

void main() {
    FrameGlobalContext ctx = GET_FRAME_CONTEXT(pc.frameGlobalContextBufferAddr);

    uint chunkId = gl_GlobalInvocationID.x;
    if (chunkId >= ctx.staticChunkCount) return;

    // 1. Fetch Chunk Data and Bounding Sphere
    StaticChunk chunk = GET_STATIC_CHUNK(ctx.staticChunkDataBufferAddr, chunkId);

    // 2. Resolve Main Camera data
    uint cameraIdx = GET_SPARSE_INDEX(ctx.cameraSparseMapBufferAddr, ctx.mainCameraEntity);
    CameraComponent camera = GET_CAMERA(ctx.cameraBufferAddr, cameraIdx);

    // 3. Frustum Culling Test
    uint visibility = INTERSECTION_INTERSECT;
    if(ctx.enableChunkFrustumCulling == 1) {
         visibility = TestAABBFrustum(chunk.minBounds, chunk.maxBounds, camera);
         if (visibility == INTERSECTION_OUTSIDE) return;
    }

    // 4. Occlusion Culling Test
    float screenSizePixels = 0.0;
    vec2 screenRes = vec2(ctx.screenWidth, ctx.screenHeight);
    bool enableDepthOcclusion = (ctx.enableChunkOcclusionCulling == 1);

    vec3 sphereCenter = (chunk.minBounds + chunk.maxBounds) * 0.5;
    float sphereRadius = length(chunk.maxBounds - sphereCenter);
    
    if (IsSphereOccludedPerspective(sphereCenter, sphereRadius, camera.view, camera.projVulkan, camera.params.x, camera.params.y, depthPyramid, screenRes, enableDepthOcclusion, screenSizePixels)) {
        return;
    }

    // WORK GRAPH ENQUEUE: If chunk is visible, dispatch a node for its models!
    allocateNodeRecordAMDX(GeometryWorkGraphStaticModelCullingNode, 1);
    
    // Encode chunk ID with visibility flag
    payloadOut.rawChunkPayload = SET_BIT_TO(chunkId, 31, visibility == INTERSECTION_INSIDE);
    
    submitNodeRecordAMDX(GeometryWorkGraphStaticModelCullingNode);
}