#version 460
#extension GL_EXT_nonuniform_qualifier : enable

layout(set = 0, binding = 0) uniform sampler2D globalTextures[];
layout(set = 1, binding = 0, r32f) uniform image2D outImage;

layout(push_constant) uniform Constants {
    uint inputTextureIndex;
} pc;

void main() {
    float value = texture(globalTextures[nonuniformEXT(pc.inputTextureIndex)], vec2(0.5)).r;
    imageStore(outImage, ivec2(gl_GlobalInvocationID.xy), vec4(value));
}