#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_ballot : require

#include "../../Includes/Core.glsl"
#include "../../Includes/Common/FrameGlobalContext.glsl"
#include "../../Includes/Common/Camera.glsl"
#include "../../Includes/Common/Transform.glsl"
#include "../../Includes/Common/Model.glsl"
#include "../../Includes/Common/Mesh.glsl"
#include "../../Includes/Common/Animation.glsl"
#include "../../Includes/Common/Material.glsl"
#include "../../Includes/Common/Culling.glsl"
#include "../../Includes/Utils/CullingMath.glsl"
#include "../../Includes/Utils/Occlusion.glsl"
#include "../../Includes/Common/StaticChunk.glsl"

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#include "../../Includes/PushConstants/ModelMeshCullingPC.glsl"

layout(push_constant) uniform PushConstants {
    ModelMeshCullingPC pc;
};

layout(set = 2, binding = 0) uniform sampler2D depthPyramid;

void main() {
    FrameGlobalContext ctx = GET_FRAME_CONTEXT(pc.frameGlobalContextBufferAddr);

    uint globalId = gl_GlobalInvocationID.x;
    if (globalId >= ctx.staticChunkCount) return; 

    // 1. Fetch Chunk Data
    StaticChunk chunk = GET_STATIC_CHUNK(ctx.staticChunkDataBufferAddr, globalId);

    // 2. Camera data
    uint cameraIdx = GET_SPARSE_INDEX(ctx.cameraSparseMapBufferAddr, ctx.mainCameraEntity);
    CameraComponent camera = GET_CAMERA(ctx.cameraBufferAddr, cameraIdx);

    // 3. Frustum Culling Test + Occlusion Culling
    uint visibility = TestAABBFrustum(chunk.minBounds, chunk.maxBounds, camera);
    if (visibility == INTERSECTION_OUTSIDE) return;

    float screenSizePixels = 0.0;
    vec2 screenRes = vec2(ctx.screenWidth, ctx.screenHeight);
    bool enableDepthOcclusion = (ctx.enableOcclusionCulling == 1);

    vec3 sphereCenter = (chunk.minBounds + chunk.maxBounds) * 0.5;
    float sphereRadius = length(chunk.maxBounds - sphereCenter);

    if (IsSphereOccluded(sphereCenter, sphereRadius, camera, depthPyramid, screenRes, enableDepthOcclusion, screenSizePixels)) {
        return;
    }

    /*
    uint needsWrite = 1;
    uint subgroupWriteCount = subgroupAdd(needsWrite);
    uint localOffset = subgroupExclusiveAdd(needsWrite);
    uint baseOffset = 0;

    if (subgroupElect()) {
        baseOffset = atomicAdd(GET_DISPATCH_CMD(ctx.modelCountBufferAddr).groupCountX, subgroupWriteCount);
    }

    baseOffset = subgroupBroadcastFirst(baseOffset);

    if (needsWrite == 1) {
        uint finalIndex = baseOffset + localOffset;
        VisibleModelData outData;

        outData.entityId = SET_BIT_TO(entityId, 31, visibility == INTERSECTION_INSIDE);
        outData.modelIndex = modelComp.modelIndex;

        GET_VISIBLE_MODEL(ctx.modelVisibleIndexBufferAddr, finalIndex) = outData;
    }
    */
}