#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_ballot : require

#include "../../../Includes/Core.glsl"
#include "../../../Includes/Common/FrameGlobalContext.glsl"
#include "../../../Includes/Common/Camera.glsl"
#include "../../../Includes/Common/Transform.glsl"
#include "../../../Includes/Common/Tag.glsl"
#include "../../../Includes/Common/Model.glsl"
#include "../../../Includes/Common/Mesh.glsl"
#include "../../../Includes/Common/Animation.glsl"
#include "../../../Includes/Common/Material.glsl"
#include "../../../Includes/Common/Culling.glsl"
#include "../../../Includes/Common/PointLight.glsl"
#include "../../../Includes/Utils/CullingMath.glsl"
#include "../../../Includes/Utils/Occlusion.glsl"
#include "../../../Includes/Utils/CullingUtils.glsl"

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#include "../../../Includes/PushConstants/PointLightShadowCullingPC.glsl"

layout(push_constant) uniform PushConstants {
    PointLightShadowCullingPC pc;
};

layout(set = 2, binding = 0) uniform sampler2D shadowDepthPyramid;

void main() 
{
    FrameGlobalContext ctx = GET_FRAME_CONTEXT(pc.frameGlobalContextBufferAddr);

    uint offset = ctx.staticTransformCount * ctx.enablePointLightBvhCulling;
    uint transformDenseIndex = gl_GlobalInvocationID.x + offset;
    uint transformCount = ctx.allTransformCount - offset;

    // 1. Thread mapping: X = Model, Y = Light Index
    uint lightIdx = gl_GlobalInvocationID.y;
    if (gl_GlobalInvocationID.x >= transformCount) return;

    uint activeShadowLightCount = GET_POINT_VISIBLE_COUNT_DATA(ctx.pointLightShadowVisibleCountBufferAddr);
    if (lightIdx >= activeShadowLightCount) return;

    // 2. Resolve Entity and Model Data
    TransformModelLink link = GET_TRANSFORM_MODEL_LINK(ctx.transformModelLinkBufferAddr, transformDenseIndex);
    if (link.modelDenseIndex == INVALID_INDEX) return;
    uint entityId = link.entityIndex;

    uint tagSparseIndex = GET_SPARSE_INDEX(ctx.tagSparseMapBufferAddr, entityId);
    if (tagSparseIndex == INVALID_INDEX) return;

    uint entityFlags = GET_TAG_DATA(ctx.tagDataBufferAddr, tagSparseIndex);
    bool isActive = (entityFlags & (1u << 0)) != 0;
    if (!isActive) return;

    ModelComponent modelComp = GET_MODEL_COMP(ctx.modelBufferAddr, link.modelDenseIndex);
    bool castShadow = (modelComp.flags & (1u << 0)) != 0;
    if (modelComp.modelIndex == INVALID_INDEX || !castShadow) return;

    // 3. Resolve Transform, Camera & Colliders
    TransformComponent transform = GET_TRANSFORM(ctx.transformBufferAddr, transformDenseIndex);
    uint cameraIdx = GET_SPARSE_INDEX(ctx.cameraSparseMapBufferAddr, ctx.mainCameraEntity);
    CameraComponent camera = GET_CAMERA(ctx.cameraBufferAddr, cameraIdx);

    ModelAllocationInfo mAlloc = GET_MODEL_ALLOC(ctx.globalModelAllocationBufferAddr, modelComp.modelIndex);
    GpuModelAddresses addrs = GET_MODEL_ADDRESSES(ctx.modelAddressBufferAddr, modelComp.modelIndex);
    GpuMeshCollider localGlobalCollider = addrs.globalCollider;

    if(ctx.animationSparseMapBufferAddr != 0) {
        uint animSparseIndex = GET_SPARSE_INDEX(ctx.animationSparseMapBufferAddr, entityId);
        if (animSparseIndex != INVALID_INDEX) {
            AnimationComponent animComp = GET_ANIM_COMP(ctx.animationBufferAddr, animSparseIndex);
            if (animComp.animationIndex != INVALID_INDEX) {
                GpuAnimationAddresses animAddrs = GET_ANIM_ADDRESSES(ctx.animationAddressBufferAddr, animComp.animationIndex);

                if (animAddrs.isReady == 1) {
                    localGlobalCollider = GET_MESH_COLLIDER(animAddrs.frameGlobalColliders, animComp.frameIndex);
                }
            }
        }
    }
    
    GpuMeshCollider worldCollider = TransformCollider(localGlobalCollider, transform.transform);

    // 4. Resolve Point Light Shadow Data
    uint lightEntity = GET_POINT_VISIBLE_SHADOW_LIGHT(ctx.pointLightVisibleShadowIndexBufferAddr, lightIdx);
    uint lightDenseIndex = GET_SPARSE_INDEX(ctx.pointLightSparseMapBufferAddr, lightEntity);
    PointLightColliderGPU lightCollider = GET_POINT_LIGHT_COLLIDER(ctx.pointLightColliderBufferAddr, lightDenseIndex);

    // 5. Composite Frustum Culling (Sphere vs Sphere + AABB)
    uint visibility = INTERSECTION_INTERSECT;
    if(ctx.enableModelFrustumCulling == 1) {
        visibility = TestSphere(worldCollider, lightCollider.center, lightCollider.radius);
        if (visibility == INTERSECTION_OUTSIDE) return;
    }

    // 6. Calculate LOD (Screen size based on Main Camera)
    float cameraNear = GET_CAMERA_NEAR(camera);
    vec2 screenRes = vec2(ctx.screenWidth, ctx.screenHeight);  
    float mainCamScreenSize = CalculateSphereScreenSizePerspective(worldCollider.center, worldCollider.radius, camera.view, camera.proj, cameraNear, screenRes);

    if (mainCamScreenSize < 1.0) return;

    uint entityData = (entityId & 0x7FFFFFFF);
    entityData = SET_BIT_TO(entityData, 31, visibility == INTERSECTION_INSIDE);

    uint safeMeshCount = mAlloc.meshAllocationCount / 4;

    // 7. Fast-Path: Direct write to Radix Sort Buffers (Small Models)
    if (IsModelSimpleEnoughForFastPath(safeMeshCount, addrs.vertexCount)) {
        
        // 8. Face Visibility (6-way Bitmask)
        uint faceMask = GetPointLightFaceVisibilityMask(worldCollider.center, worldCollider.radius, lightCollider.center);
        if (faceMask == 0u) return;

        //Todo: Mesh facemasks?

        uint rawLod = CalculateLodFromScreenSize(mainCamScreenSize);
        uint lod = min(rawLod + ctx.pointLightShadowLodBias, 3u);

        for(uint m = 0; m < safeMeshCount; ++m) {
            uint matIdx = GET_MATERIAL_INDEX(ctx.materialLookupBufferAddr, modelComp.materialOffset + m);
            Material mat = GET_MATERIAL(ctx.materialBufferAddr, matIdx);

            uint matType = GetMaterialRenderType(mat);
            if (matType > 3) continue;

            MeshAllocationInfo meshAlloc = GET_MESH_ALLOC(ctx.globalMeshAllocationBufferAddr, mAlloc.meshAllocationOffset + (m * 4) + lod);
            uint pipeIdx = GET_PIPELINE_INDEX(ctx.pipelineLookupBufferAddr, modelComp.pipelineOffset + m);

            if (meshAlloc.activeTypes[pipeIdx][matType] == 1) {
                uint indirectIdx = meshAlloc.indirectIndices[pipeIdx][matType];
                uint isMeshlet = (pipeIdx == PIPELINE_MESHLET) ? 1u : 0u;
                uint drawCallKey = (isMeshlet << 31) | (indirectIdx & 0x7FFFFFFF);

                for (uint f = 0; f < 6; ++f) {
                    if ((faceMask & (1u << f)) != 0u) {
                        uint lightDataPacked = (f << 29) | (lightIdx & 0x1FFFFFFF);
                        uvec2 gpuPayload = uvec2(entityData, lightDataPacked);

                        uint sortSlot = atomicAdd(GET_POINT_VISIBLE_COUNT_DATA(ctx.pointLightShadowVisibleMeshCountBufferAddr), 1);
                        GET_POINT_DRAW_CALL_KEY_DATA(ctx.pointLightShadowDrawCallKeyBufferAddr, sortSlot) = drawCallKey;
                        GET_POINT_SORTED_VALUE(ctx.pointLightShadowSortValuesBufferAddr, sortSlot) = sortSlot;
                        GET_POINT_SHADOW_INSTANCE_UNSORTED(ctx.pointLightShadowUnsortedInstanceBufferAddr, sortSlot) = gpuPayload;
                    }
                }
            }
        }
        return;
    }

    // 9. Slow-Path: Defer to Mesh Culling
    uint needsWrite = 1;
    uint subgroupWriteCount = subgroupAdd(needsWrite);
    uint localOffset = subgroupExclusiveAdd(needsWrite);
    uint baseOffset = 0;

    if (subgroupElect()) {
        baseOffset = atomicAdd(GET_DISPATCH_CMD(ctx.pointLightShadowModelCountBufferAddr).groupCountX, subgroupWriteCount);
    }

    baseOffset = subgroupBroadcastFirst(baseOffset);

    if (needsWrite == 1) {
        uint finalIndex = baseOffset + localOffset;
        uint modelPayload = (modelComp.modelIndex & 0xFFFFFu);
        modelPayload |= ((lightIdx & 0xFFFu) << 20);

        VisibleModelData outData;
        outData.entityId = entityData;
        outData.modelIndex = modelPayload; // [Bits 20-31: LightIdx, Bits 0-19: pureModelIndex]
        
        GET_VISIBLE_MODEL(ctx.pointLightShadowModelVisibleIndexBufferAddr, finalIndex) = outData;
    }
}