// Copyright (C) 2026 Tamás Péter
// This file is part of SynapseEngine.
//
// SynapseEngine is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SynapseEngine is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with SynapseEngine. If not, see <https://www.gnu.org/licenses/>.

#version 460
#extension GL_GOOGLE_include_directive : require

#include "../../Includes/Core.glsl"
#include "../../Includes/Utils/EnvironmentMath.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 2, binding = 0, rg32f) uniform writeonly image2D outBrdfLut;

layout(push_constant) uniform PushConstants {
    uint sampleCount;
} pc;

void main() {
    ivec2 imgSize = imageSize(outBrdfLut);
    ivec2 id = ivec2(gl_GlobalInvocationID.xy);
    
    if (id.x >= imgSize.x || id.y >= imgSize.y) return;
    vec2 uv = vec2(id) / vec2(imgSize.x - 1.0, imgSize.y - 1.0);
    
    float NdotV = clamp(uv.x, 0.001, 1.0);
    float roughness = clamp(uv.y, 0.001, 1.0);

    vec3 V = vec3(sqrt(clamp(1.0 - NdotV * NdotV, 0.0, 1.0)), 0.0, NdotV);
    vec3 N = vec3(0.0, 0.0, 1.0);
    
    float A = 0.0;
    float B = 0.0;
    float a2 = roughness * roughness;
    
    uint SAMPLE_COUNT = pc.sampleCount;

    for(uint i = 0u; i < SAMPLE_COUNT; ++i) {
        vec2 Xi = Hammersley(i, SAMPLE_COUNT);
        vec3 H = ImportanceSampleGGX(Xi, N, roughness);
        
        vec3 unormL = 2.0 * dot(V, H) * H - V;
        float lenL = length(unormL);
        if (lenL < 0.00001) continue; 
        vec3 L = unormL / lenL;

        float NdotL = max(L.z, 0.0);
        float NdotH = max(H.z, 0.0);
        float VdotH = max(dot(V, H), 0.0);

        if (NdotL > 0.0) {
            float ggxV = NdotL * sqrt(max(NdotV * NdotV * (1.0 - a2) + a2, 0.0));
            float ggxL = NdotV * sqrt(max(NdotL * NdotL * (1.0 - a2) + a2, 0.0));

            float Vis = 0.5 / (ggxV + ggxL + 1e-5);
            float G_Vis = Vis * (4.0 * NdotL * VdotH) / max(NdotH, 0.001);
            float Fc_base = clamp(1.0 - VdotH, 0.0, 1.0);
            float Fc2 = Fc_base * Fc_base;
            float Fc = Fc2 * Fc2 * Fc_base;

            if (!isnan(G_Vis) && !isinf(G_Vis)) {
                A += (1.0 - Fc) * G_Vis;
                B += Fc * G_Vis;
            }
        }
    }

    A /= float(SAMPLE_COUNT);
    B /= float(SAMPLE_COUNT);

    imageStore(outBrdfLut, id, vec4(A, B, 0.0, 1.0));
}