#version 460
#extension GL_GOOGLE_include_directive : require

#include "../../Includes/Core.glsl"
#include "../../Includes/Utils/EnvironmentMath.glsl"

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 2, binding = 0) uniform sampler2D sourceMap;
layout(set = 2, binding = 1, rgba16f) uniform writeonly imageCube targetCube;

void main() {
    ivec3 cubeCoord = ivec3(gl_GlobalInvocationID);
    ivec2 size = imageSize(targetCube);
    
    if(cubeCoord.x >= size.x || cubeCoord.y >= size.y) return;
    
    vec2 uv = vec2(cubeCoord.xy) / vec2(size.xy);
    vec3 dir = GetCubeDir(uv, cubeCoord.z);
    
    vec2 sphericUV = SampleEquirectangular(dir);
    sphericUV.y = 1.0 - sphericUV.y;

    vec4 color = texture(sourceMap, sphericUV);
    
    imageStore(targetCube, cubeCoord, color);
}