#version 460
#extension GL_GOOGLE_include_directive : require

#include "../../Includes/Core.glsl"
#include "../../Includes/Utils/EnvironmentMath.glsl"

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(set = 2, binding = 0) uniform samplerCube environmentMap;
layout(set = 2, binding = 1, rgba16f) uniform writeonly imageCube irradianceMap;

void main() {
    ivec3 cubeCoord = ivec3(gl_GlobalInvocationID);
    ivec2 size = imageSize(irradianceMap);
    
    if(cubeCoord.x >= size.x || cubeCoord.y >= size.y) return;
    
    vec2 uv = vec2(cubeCoord.xy) / vec2(size.xy);
    vec3 normal = GetCubeDir(uv, cubeCoord.z);
    
    vec3 irradiance = vec3(0.0);
    vec3 up = vec3(0.0, 1.0, 0.0);
    vec3 right = normalize(cross(up, normal));
    up = normalize(cross(normal, right));
    
    float sampleDelta = 0.025;
    float nrSamples = 0.0;
    
    for(float phi = 0.0; phi < 2.0 * PI; phi += sampleDelta) {
        for(float theta = 0.0; theta < 0.5 * PI; theta += sampleDelta) {
            vec3 tangentSample = vec3(sin(theta) * cos(phi), sin(theta) * sin(phi), cos(theta));
            vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * normal;
            
            irradiance += texture(environmentMap, sampleVec).rgb * cos(theta) * sin(theta);
            nrSamples++;
        }
    }
    
    irradiance = PI * irradiance * (1.0 / float(nrSamples));
    imageStore(irradianceMap, cubeCoord, vec4(irradiance, 1.0));
}