#version 460
layout (local_size_x = 64, local_size_y = 64, local_size_z = 1) in;

#include "Common/Camera.glsl"
#include "Common/Count.glsl"
#include "Common/Render/InstanceIndex.glsl"
#include "Common/Render/RenderIndices.glsl"

#include "Common/Render/DrawIndirect.glsl"
#include "Common/Render/DefaultCollider.glsl"
#include "Common/Light/PointLight.glsl"
#include "Common/Light/LightCommon.glsl"

#include "Common/Culling/Culling.glsl"

layout(push_constant) uniform constants
{	
	uvec2 defaultColliderBuffer;
	uvec2 defaultColliderCountBuffer;
	uvec2 defaultColliderCulledIndexBuffer;

	uvec2 pointLightBuffer;
	uvec2 pointLightCommonDataBuffer;
	uvec2 pointLightShadowInstanceIndexBuffer;
	uvec2 pointLightShadowIndexMapBuffer;

	//These are an NxM buffer matrix of instance indices! N shadow point light + M loaded (model/shape)
	//These are an NxM buffer matrix of indirect draw commands! N shadow point light + M loaded (model/shape)

	uvec2 modelRenderIndicesBuffer;
	uvec2 pointLightShadowModelInstanceBufferAddresses;
	uvec2 pointLightShadowModelIndirectDrawBufferAddresses;

	uvec2 shapeRenderIndicesBuffer;
	uvec2 pointLightShadowShapeInstanceBufferAddresses;
	uvec2 pointLightShadowShapeIndirectDrawBufferAddresses;

	//Todo: Kell egy point light index -> Shadow index leképezés! 
	//Ehhez is külön index buffer?
} PushConstants;

void main()
{
	uint lightIndex = gl_GlobalInvocationID.x;
	uint colliderInstanceIndex = gl_GlobalInvocationID.y;

	CountBuffer defaultColliderCountBuffer = CountBuffer(PushConstants.defaultColliderCountBuffer);
	LightCommonDataBuffer lightCommonDataBuffer = LightCommonDataBuffer(PushConstants.pointLightCommonDataBuffer);

	if(lightIndex >= lightCommonDataBuffer.commonData.shadowCount || colliderInstanceIndex >= defaultColliderCountBuffer.count)
		return;

	InstanceIndexBuffer defaultColliderCulledIndexBuffer = InstanceIndexBuffer(PushConstants.defaultColliderCulledIndexBuffer);
	uint colliderIndex = defaultColliderCulledIndexBuffer.indices[colliderInstanceIndex];
	
	DefaultColliderBuffer defaultColliderBuffer = DefaultColliderBuffer(PushConstants.defaultColliderBuffer);
	uint objectIndex = defaultColliderBuffer.colliders[colliderIndex].objectIndex;

	if(objectIndex == INVALID_RENDER_INDEX)
		return;

	PointLightBuffer pointLightBuffer = PointLightBuffer(PushConstants.pointLightBuffer);
	uint pointLightIndex = InstanceIndexBuffer(PushConstants.pointLightShadowInstanceIndexBuffer).indices[lightIndex];

	vec3 objectAabbMin = defaultColliderBuffer.colliders[colliderIndex].aabbOrigin - defaultColliderBuffer.colliders[colliderIndex].aabbExtents;
	vec3 objectAabbMax = defaultColliderBuffer.colliders[colliderIndex].aabbOrigin + defaultColliderBuffer.colliders[colliderIndex].aabbExtents;	

	vec3 sphereOrigin = pointLightBuffer.lights[pointLightIndex].position;
	float sphereRadius = pointLightBuffer.lights[pointLightIndex].radius;

	if(TestAabbVsSphere(objectAabbMin, objectAabbMax, sphereOrigin, sphereRadius))
	{
		uint pointLightShadowIndex = lightIndex; //Todo: Map point light index to shadow index!
		bool isModel = (defaultColliderBuffer.colliders[colliderIndex].bitflag & COLLIDER_MODEL_BIT) != 0u;

		if(isModel)
		{
			uvec2 instanceIndexBufferAddress = InstanceIndexAddressBuffer(PushConstants.pointLightShadowModelInstanceBufferAddresses).deviceAddresses[pointLightShadowIndex];
			uvec2 drawIndirectBufferAddress = InstanceIndexAddressBuffer(PushConstants.pointLightShadowModelIndirectDrawBufferAddresses).deviceAddresses[pointLightShadowIndex];

			uint modelIndex = ModelRenderIndicesBuffer(PushConstants.modelRenderIndicesBuffer).indices[objectIndex].modelIndex;			
			
			uint instanceIndex = atomicAdd(DrawIndirectCommandBuffer(drawIndirectBufferAddress).commands[modelIndex].instanceCount, 1);		
			InstanceIndexBuffer(instanceIndexBufferAddress).indices[instanceIndex] = objectIndex;
		}
		else
		{
			uvec2 instanceIndexBufferAddress = InstanceIndexAddressBuffer(PushConstants.pointLightShadowShapeInstanceBufferAddresses).deviceAddresses[pointLightShadowIndex];
			uvec2 drawIndirectBufferAddress = InstanceIndexAddressBuffer(PushConstants.pointLightShadowShapeIndirectDrawBufferAddresses).deviceAddresses[pointLightShadowIndex];

			uint shapeIndex = ShapeRenderIndicesBuffer(PushConstants.shapeRenderIndicesBuffer).indices[objectIndex].shapeIndex;			

			uint instanceIndex = atomicAdd(DrawIndirectCommandBuffer(drawIndirectBufferAddress).commands[shapeIndex].instanceCount, 1);		
			InstanceIndexBuffer(instanceIndexBufferAddress).indices[instanceIndex] = objectIndex;
		}
	}
}