#include "SceneSettings.h"

namespace Syn
{
    SceneSettings::SceneSettings()
		: pipelineType(PipelineType::ForwardPlus)
        , useDebugCamera(false)
        , enableGpuCulling(true)
        , enableBloom(true)
        , enableHiz(true)
        , enableOcclusionCulling(true)
        , enableConeCulling(true)
        , enableFrustumCulling(true)
        , enablePointLightSphereWireframe(false)
        , enablePointLightAabbWireframe(false)
        , enableSpotLightSphereWireframe(false)
        , enableSpotLightAabbWireframe(false)
        , enableWireframeMeshAabb(false)
        , enableWireframeMeshSphere(false)
        , enableDeferredEmissiveAo(true)
        , enableDeferredPointLights(true)
        , enableDeferredSpotLights(true)
        , enableDeferredDirectionalLights(true)
        , enableBillboardCameras(true)
        , enableBillboardPointLights(true)
        , enableBillboardSpotLights(true)
        , enableBillboardDirectionalLights(true)
        , ambientStrength(0.05f)
        , emissiveStrength(1.00f)
		, bloomThreshold(1.0f)
		, bloomKnee(0.1f)
        , bloomFilterRadius(0.005f)
        , bloomExposure(1.0f)
        , bloomStrength(1.0f)
        , enableDebugVisibility(false)
        , debugVisibilityMode(DebugVisibilityMode::AllCombined)
    {}
}