#version 460
#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_ballot : require

#include "../../../../Includes/Core.glsl"
#include "../../../../Includes/Common/Camera.glsl"
#include "../../../../Includes/Common/Cluster.glsl"
#include "../../../../Includes/Common/SpotLight.glsl"
#include "../../../../Includes/Utils/CullingMath.glsl" 
#include "../../../../Includes/Utils/ClusterMath.glsl"
#include "../../../../Includes/Common/IndirectCommand.glsl"

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

#include "../../../../Includes/PushConstants/ClusterLightCountPC.glsl"

layout(push_constant) uniform PushConstants {
    ClusterLightCountPC pc;
};

shared uint s_localSpotLightCount;
shared vec3 s_clusterAABBMin;
shared vec3 s_clusterAABBMax;

void main() {
    uint threadId = gl_LocalInvocationID.x;
    uint clusterIdx = gl_WorkGroupID.x;
    
    uint activeClusterCount = GET_CLUSTER_COUNT(pc.clusterCountAddr);
    if (clusterIdx >= activeClusterCount) return;
    
    uint totalLights = GET_VK_DRAW_CMD(pc.lightIndirectCmdAddr, 0).instanceCount;
    uint cameraIdx = GET_SPARSE_INDEX(pc.cameraSparseMapBufferAddr, pc.activeCameraEntity);
    CameraComponent camera = GET_CAMERA(pc.cameraBufferAddr, cameraIdx);

    if (threadId == 0) {
        s_localSpotLightCount = 0;     
        ClusterData cluster = GET_CLUSTER_DATA(pc.clusterListAddr, clusterIdx);

        GetClusterViewSpaceAABB(
            cluster.tileIndex, pc.tileCountX, pc.tileSize, pc.screenWidth, pc.screenHeight, 
            cluster.minZ, cluster.maxZ, camera.projVulkanInv, 
            s_clusterAABBMin, s_clusterAABBMax
        );
    }

    barrier();

    for (uint i = threadId; i < totalLights; i += gl_WorkGroupSize.x) {
        uint entityIdx = GET_VISIBLE_SPOT_LIGHT(pc.visibleLightAddr, i);
        SpotLightColliderGPU collider = GET_SPOT_LIGHT_COLLIDER(pc.lightColliderDataAddr, entityIdx);
        
        vec3 viewSpaceCenter = collider.viewSpaceCenter;
        bool isIntersecting = TestSphereAABB(viewSpaceCenter, collider.radius, s_clusterAABBMin, s_clusterAABBMax);

        uvec4 ballot = subgroupBallot(isIntersecting);
        uint activeCount = subgroupBallotBitCount(ballot);

        if (subgroupElect() && activeCount > 0) {
            atomicAdd(s_localSpotLightCount, activeCount);
        }
    }

    barrier();
  
    if (threadId == 0) {
        GET_CLUSTER_DATA(pc.clusterListAddr, clusterIdx).spotLightCount = s_localSpotLightCount;
    }
}